# Generated by Django 5.0.4 on 2024-04-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('D', 'Director'), ('S', 'Screen Writer'), ('P', 'Producer')], max_length=1)),
                ('name', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('1', 'Action'), ('2', 'Adventure'), ('3', 'Animation'), ('4', 'Comedy'), ('5', 'Crime'), ('6', 'Documentary'), ('7', 'Drama'), ('8', 'Fantasy'), ('9', 'Horror'), ('10', 'Musical'), ('11', 'Mystery'), ('12', 'Romance'), ('13', 'Science Fiction'), ('14', 'Thriller'), ('15', 'War'), ('16', 'Western')], max_length=2)),
                ('description', models.TextField(max_length=500)),
                ('release_year', models.IntegerField(max_length=4)),
                ('actor', models.ManyToManyField(to='main_app.actor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod_mem', models.ManyToManyField(to='main_app.prod_mem')),
            ],
        ),
    ]
