# Generated by Django 5.0.4 on 2024-04-21 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(error_messages={'invalid': 'Enter a valid year between 1900 and 2049'}, validators=[django.core.validators.RegexValidator(message='Enter a valid year between 1900 and 2049', regex='^19\\d{2}|20[0-4]\\d$')]),
        ),
    ]
