# Generated by Django 4.2.11 on 2024-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
